//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSatis.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OneCikanlar
    {
        public int OneCikanlarId { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> Like_LikeId { get; set; }
        public Nullable<int> Yorum_YorumId { get; set; }
        public string ResimURL { get; set; }
    
        public virtual Like Like { get; set; }
        public virtual Yorum Yorum { get; set; }
    }
}
