//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSatis.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis
    {
        public int SatisId { get; set; }
        public System.Guid MusteriId { get; set; }
        public System.DateTime SatisTarihi { get; set; }
        public decimal ToplamTutar { get; set; }
        public bool SepetteMi { get; set; }
        public int KargoId { get; set; }
        public int SiparisDurumId { get; set; }
        public string KargoTakipNo { get; set; }
        public Nullable<int> Musteri_MusteriId { get; set; }
        public Nullable<int> SatisDetay_SatisId { get; set; }
    
        public virtual Kargo Kargo { get; set; }
        public virtual Musteri Musteri { get; set; }
        public virtual SiparisDurum SiparisDurum { get; set; }
    }
}
