//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSatis.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SepetUrunu
    {
        public string SepetUrunId { get; set; }
        public string SeptId { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<System.DateTime> OluşturmaTarihi { get; set; }
        public Nullable<int> UrunId { get; set; }
    
        public virtual Urun Urun { get; set; }
    }
}
